[[main]]
  name = "Documentation"
  url = 'https://docs.thulite.io'
  weight = 10

[[main]]
  name = "Blog"
  pageRef = '/blog'
  weight = 20

[[main]]
  name = "Resources"
  pageRef = '/resources'
  weight = 40

[[main]]
  name = "Showcase"
  pageRef = '/showcase'
  parent = "Resources"
  weight = 43

[[main]]
  name = "Templates"
  pageRef = '/templates'
  parent = "Resources"
  weight = 45

[[main]]
  name = "Integrations"
  pageRef = '/integrations'
  parent = "Resources"
  weight = 47

[[main]]
  name = "Community"
  url = 'https://github.com/orgs/thuliteio/discussions'
  weight = 50

[[social]]
  name = "GitHub"
  pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/></svg>'
  url = "https://github.com/thuliteio/thulite"
  weight = 10

# [[social]]
#   name = "Mastodon"
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-mastodon" viewBox="0 0 16 16"><path d="M11.19 12.195c2.016-.24 3.77-1.475 3.99-2.603.348-1.778.32-4.339.32-4.339 0-3.47-2.286-4.488-2.286-4.488C12.062.238 10.083.017 8.027 0h-.05C5.92.017 3.942.238 2.79.765c0 0-2.285 1.017-2.285 4.488l-.002.662c-.004.64-.007 1.35.011 2.091.083 3.394.626 6.74 3.78 7.57 1.454.383 2.703.463 3.709.408 1.823-.1 2.847-.647 2.847-.647l-.06-1.317s-1.303.41-2.767.36c-1.45-.05-2.98-.156-3.215-1.928a4 4 0 0 1-.033-.496s1.424.346 3.228.428c1.103.05 2.137-.064 3.188-.189zm1.613-2.47H11.13v-4.08c0-.859-.364-1.295-1.091-1.295-.804 0-1.207.517-1.207 1.541v2.233H7.168V5.89c0-1.024-.403-1.541-1.207-1.541-.727 0-1.091.436-1.091 1.296v4.079H3.197V5.522q0-1.288.66-2.046c.456-.505 1.052-.764 1.793-.764.856 0 1.504.328 1.933.983L8 4.39l.417-.695c.429-.655 1.077-.983 1.934-.983.74 0 1.336.259 1.791.764q.662.757.661 2.046z"/></svg>'
#   url = "https://fosstodon.org/@thulite"
#   weight = 20

# [[social]]
#   name = "Open Collective"
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-opencollective" viewBox="0 0 16 16"><path fill-opacity=".4" d="M12.995 8.195c0 .937-.312 1.912-.78 2.693l1.99 1.99c.976-1.327 1.6-2.966 1.6-4.683 0-1.795-.624-3.434-1.561-4.76l-2.068 2.028c.468.781.78 1.679.78 2.732z"/><path d="M8 13.151a4.995 4.995 0 1 1 0-9.99c1.015 0 1.951.273 2.732.82l1.95-2.03a7.805 7.805 0 1 0 .04 12.449l-1.951-2.03a5.07 5.07 0 0 1-2.732.781z"/></svg>'
#   url = "https://opencollective.com/thulite"
#   weight = 30

# [[social]]
#   name = "X"
#   pre= '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16"><path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/></svg>'
#   url = "https://x.com/thuliteio"
#   weight = 40

[[legal]]
  name = "Privacy Policy"
  pageRef = '/privacy'
  weight = 10

[[legal]]
  name = "Terms of Service"
  pageRef = '/terms'
  weight = 20

# [[legal]]
#   name = "Status"
#   url = 'https://status.thulite.io/'
#   weight = 30

[[sponsors]]
  name = "Netlify"
  url = "https://www.netlify.com/?utm_campaign=Thulite-2025&utm_source=thulite-referral"
  weight = 10

[[sponsors]]
  name = "Algolia"
  url = "https://www.algolia.com/?utm_campaign=Thulite-2025&utm_source=thulite-referral"
  weight = 20

[[sponsors]]
  name = "Infisical"
  url = "https://infisical.com/?utm_campaign=Thulite-2025&utm_source=thulite-referral"
  weight = 30

[[sponsors]]
  name = "Instatus"
  url = "https://instatus.com/?utm_campaign=Thulite-2025&utm_source=thulite-referral"
  weight = 40

[[documentation]]
  name = "Thulite"
  url = "https://docs.thulite.io/"
  weight = 10

[[documentation]]
  name = "SEO"
  url = "https://seo.thulite.io/"
  weight = 20

[[documentation]]
  name = "Images"
  url = "https://images.thulite.io/"
  weight = 30

[[documentation]]
  name = "SVG"
  url = "https://svg.thulite.io/"
  weight = 40

[[documentation]]
  name = "Doks"
  url = "https://getdoks.org/"
  weight = 50

# [[resources]]
#   name = "Blog"
#   pageRef = '/blog'
#   weight = 10

[[resources]]
  name = "Showcase"
  pageRef = '/showcase'
  weight = 10

[[resources]]
  name = "Templates"
  pageRef = '/templates'
  weight = 20

[[resources]]
  name = "Integrations"
  pageRef = '/integrations'
  weight = 30

[[community]]
  name = "GitHub"
  url = "https://github.com/orgs/thuliteio/discussions"
  weight = 10

[[community]]
  name = "Mastodon"
  url = "https://fosstodon.org/@thulite"
  weight = 20

[[community]]
  name = "Open Collective"
  url = "https://opencollective.com/thulite"
  weight = 30
