[[main]]
  name = "Documentation"
  url = "https://docs.gethyas.com/"
  weight = 10

[[main]]
  name = "Showcase"
  url = "/showcase/"
  weight = 20

[[main]]
  name = "Resources"
  identifier = "resources"
  url = "/products/"
  weight = 30

[[main]]
  name = "Themes"
  parent = "resources"
  url = "/themes/"
  weight = 33
  # pre = '<svg data-hk="0-0" width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 "><path d="M7.42002 15.5399C7.23377 15.7273 7.12923 15.9807 7.12923 16.2449C7.12923 16.5091 7.23377 16.7625 7.42002 16.9499C7.51298 17.0436 7.62358 17.118 7.74544 17.1688C7.8673 17.2196 7.99801 17.2457 8.13002 17.2457C8.26203 17.2457 8.39274 17.2196 8.5146 17.1688C8.63646 17.118 8.74706 17.0436 8.84002 16.9499C9.02627 16.7625 9.13081 16.5091 9.13081 16.2449C9.13081 15.9807 9.02627 15.7273 8.84002 15.5399C8.74706 15.4462 8.63646 15.3718 8.5146 15.321C8.39274 15.2702 8.26203 15.2441 8.13002 15.2441C7.99801 15.2441 7.8673 15.2702 7.74544 15.321C7.62358 15.3718 7.51298 15.4462 7.42002 15.5399ZM7.42002 7.04989C7.23377 7.23726 7.12923 7.49071 7.12923 7.75489C7.12923 8.01908 7.23377 8.27253 7.42002 8.45989C7.51298 8.55362 7.62358 8.62802 7.74544 8.67879C7.8673 8.72955 7.99801 8.75569 8.13002 8.75569C8.26203 8.75569 8.39274 8.72955 8.5146 8.67879C8.63646 8.62802 8.74706 8.55362 8.84002 8.45989C9.02627 8.27253 9.13081 8.01908 9.13081 7.75489C9.13081 7.49071 9.02627 7.23726 8.84002 7.04989C8.74706 6.95617 8.63646 6.88177 8.5146 6.831C8.39274 6.78023 8.26203 6.7541 8.13002 6.7541C7.99801 6.7541 7.8673 6.78023 7.74544 6.831C7.62358 6.88177 7.51298 6.95617 7.42002 7.04989ZM12.37 17.0499C12.1722 17.0499 11.9789 17.1085 11.8145 17.2184C11.65 17.3283 11.5218 17.4845 11.4461 17.6672C11.3705 17.8499 11.3506 18.051 11.3892 18.245C11.4278 18.439 11.5231 18.6171 11.6629 18.757C11.8028 18.8969 11.9809 18.9921 12.1749 19.0307C12.3689 19.0693 12.57 19.0495 12.7527 18.9738C12.9354 18.8981 13.0916 18.7699 13.2015 18.6055C13.3114 18.441 13.37 18.2477 13.37 18.0499C13.3768 17.9144 13.356 17.779 13.3087 17.6518C13.2615 17.5247 13.189 17.4085 13.0954 17.3102C13.0019 17.212 12.8893 17.1339 12.7646 17.0805C12.6399 17.0272 12.5057 16.9997 12.37 16.9999V17.0499ZM6.37002 11.0499C6.17224 11.0499 5.9789 11.1085 5.81445 11.2184C5.65 11.3283 5.52183 11.4845 5.44614 11.6672C5.37045 11.8499 5.35065 12.051 5.38924 12.245C5.42782 12.439 5.52306 12.6171 5.66291 12.757C5.80277 12.8969 5.98095 12.9921 6.17493 13.0307C6.36891 13.0693 6.56998 13.0495 6.7527 12.9738C6.93543 12.8981 7.09161 12.7699 7.20149 12.6055C7.31137 12.441 7.37002 12.2477 7.37002 12.0499C7.3768 11.9144 7.35595 11.779 7.30875 11.6518C7.26154 11.5247 7.18895 11.4085 7.09541 11.3102C7.00187 11.212 6.88932 11.1339 6.76462 11.0805C6.63991 11.0272 6.50566 10.9997 6.37002 10.9999V11.0499ZM12.37 5.04989C12.1722 5.04989 11.9789 5.10854 11.8145 5.21842C11.65 5.32831 11.5218 5.48449 11.4461 5.66721C11.3705 5.84994 11.3506 6.051 11.3892 6.24499C11.4278 6.43897 11.5231 6.61715 11.6629 6.757C11.8028 6.89685 11.9809 6.99209 12.1749 7.03068C12.3689 7.06926 12.57 7.04946 12.7527 6.97377C12.9354 6.89809 13.0916 6.76991 13.2015 6.60546C13.3114 6.44102 13.37 6.24768 13.37 6.04989C13.3768 5.91443 13.356 5.779 13.3087 5.65184C13.2615 5.52468 13.189 5.40846 13.0954 5.31024C13.0019 5.21202 12.8893 5.13385 12.7646 5.0805C12.6399 5.02715 12.5057 4.99972 12.37 4.99989V5.04989ZM15.91 7.09989C15.7696 7.23951 15.6737 7.41768 15.6347 7.61182C15.5956 7.80597 15.6151 8.00734 15.6906 8.19041C15.7661 8.37348 15.8943 8.53001 16.0588 8.64016C16.2234 8.7503 16.417 8.8091 16.615 8.8091C16.8131 8.8091 17.0066 8.7503 17.1712 8.64016C17.3358 8.53001 17.464 8.37348 17.5395 8.19041C17.615 8.00734 17.6344 7.80597 17.5954 7.61182C17.5563 7.41768 17.4605 7.23951 17.32 7.09989C17.1393 6.90685 16.8896 6.79321 16.6253 6.78384C16.3611 6.77447 16.1039 6.87013 15.91 7.04989V7.09989ZM22.21 7.09989C21.2958 5.27219 19.8904 3.73531 18.1516 2.6616C16.4128 1.58788 14.4092 1.01978 12.3656 1.021C10.322 1.02222 8.31914 1.59271 6.5816 2.66851C4.84407 3.7443 3.44057 5.28286 2.5285 7.11166C1.61643 8.94045 1.23184 10.9872 1.41787 13.0223C1.60389 15.0574 2.35317 17.0005 3.58169 18.6336C4.8102 20.2668 6.46938 21.5254 8.37316 22.2683C10.2769 23.0113 12.35 23.2092 14.36 22.8399C14.8655 22.7448 15.3469 22.5499 15.7761 22.2666C16.2054 21.9833 16.5739 21.6172 16.86 21.1899C17.1684 20.7253 17.3811 20.2039 17.4858 19.6562C17.5906 19.1086 17.5852 18.5455 17.47 17.9999C17.407 17.6702 17.3736 17.3355 17.37 16.9999C17.3744 16.0309 17.6603 15.084 18.1929 14.2744C18.7255 13.4648 19.4819 12.8275 20.37 12.4399C20.8489 12.2255 21.2787 11.9152 21.633 11.5282C21.9873 11.1413 22.2586 10.6858 22.43 10.1899C22.6034 9.68318 22.6733 9.1468 22.6355 8.61258C22.5977 8.07835 22.453 7.55715 22.21 7.07989V7.09989ZM20.51 9.53989C20.4247 9.77921 20.2922 9.99898 20.1205 10.1862C19.9487 10.3734 19.7411 10.5243 19.51 10.6299C18.28 11.1805 17.2351 12.0744 16.5007 13.2044C15.7663 14.3343 15.3737 15.6523 15.37 16.9999C15.3715 17.47 15.4184 17.9388 15.51 18.3999C15.5711 18.6817 15.5751 18.9729 15.5219 19.2562C15.4686 19.5396 15.3592 19.8095 15.2 20.0499C15.0653 20.2603 14.8881 20.4402 14.6797 20.578C14.4713 20.7157 14.2364 20.8084 13.99 20.8499C13.4559 20.9503 12.9135 21.0005 12.37 20.9999C11.1642 21.0005 9.97054 20.7587 8.85994 20.289C7.74935 19.8193 6.74447 19.1313 5.90498 18.2656C5.06549 17.4 4.4085 16.3745 3.97304 15.2501C3.53757 14.1256 3.33251 12.9251 3.37002 11.7199C3.44763 9.47269 4.35903 7.33485 5.92665 5.72286C7.49428 4.11086 9.60585 3.14018 11.85 2.99989H12.36C14.0358 3.00031 15.6781 3.46858 17.1021 4.35196C18.5261 5.23534 19.6752 6.49874 20.42 7.99989C20.6493 8.47488 20.6816 9.02118 20.51 9.51989V9.53989ZM12.37 10.9999C12.1722 10.9999 11.9789 11.0585 11.8145 11.1684C11.65 11.2783 11.5218 11.4345 11.4461 11.6172C11.3705 11.7999 11.3506 12.001 11.3892 12.195C11.4278 12.389 11.5231 12.5671 11.6629 12.707C11.8028 12.8469 11.9809 12.9421 12.1749 12.9807C12.3689 13.0193 12.57 12.9995 12.7527 12.9238C12.9354 12.8481 13.0916 12.7199 13.2015 12.5555C13.3114 12.391 13.37 12.1977 13.37 11.9999C13.37 11.7347 13.2647 11.4803 13.0771 11.2928C12.8896 11.1053 12.6352 10.9999 12.37 10.9999Z" fill="currentColor"></path></svg>'
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-palette" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 21a9 9 0 0 1 0 -18c4.97 0 9 3.582 9 8c0 1.06 -.474 2.078 -1.318 2.828c-.844 .75 -1.989 1.172 -3.182 1.172h-2.5a2 2 0 0 0 -1 3.75a1.3 1.3 0 0 1 -1 2.25"></path><path d="M8.5 10.5m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path><path d="M12.5 7.5m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path><path d="M16.5 10.5m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path></svg>'

[[main]]
  name = "Integrations"
  parent = "resources"
  url = "/integrations/"
  weight = 35
  # pre = '<svg data-hk="0-0" width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 "><path d="M21 2H9C8.73478 2 8.48043 2.10536 8.29289 2.29289C8.10536 2.48043 8 2.73478 8 3V7H6C5.73478 7 5.48043 7.10536 5.29289 7.29289C5.10536 7.48043 5 7.73478 5 8V12H3C2.73478 12 2.48043 12.1054 2.29289 12.2929C2.10536 12.4804 2 12.7348 2 13V21C2 21.2652 2.10536 21.5196 2.29289 21.7071C2.48043 21.8946 2.73478 22 3 22H11C11.2652 22 11.5196 21.8946 11.7071 21.7071C11.8946 21.5196 12 21.2652 12 21V19H16C16.2652 19 16.5196 18.8946 16.7071 18.7071C16.8946 18.5196 17 18.2652 17 18V16H21C21.2652 16 21.5196 15.8946 21.7071 15.7071C21.8946 15.5196 22 15.2652 22 15V3C22 2.73478 21.8946 2.48043 21.7071 2.29289C21.5196 2.10536 21.2652 2 21 2ZM10 20H4V14H10V20ZM15 17H12V13C12 12.7348 11.8946 12.4804 11.7071 12.2929C11.5196 12.1054 11.2652 12 11 12H7V9H15V17ZM20 14H17V8C17 7.73478 16.8946 7.48043 16.7071 7.29289C16.5196 7.10536 16.2652 7 16 7H10V4H20V14Z" fill="currentColor"></path></svg>'
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-stack-2" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 4l-8 4l8 4l8 -4l-8 -4"></path><path d="M4 12l8 4l8 -4"></path><path d="M4 16l8 4l8 -4"></path></svg>'

# [[main]]
#   name = "Guides"
#   parent = "resources"
#   url = "https://docs.gethyas.com/guides/"
#   weight = 37
#   # pre = '<svg data-hk="0-0" width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 "><path d="M21.17 2.06012C20.4532 1.93665 19.7274 1.8731 19 1.87012C16.5184 1.86809 14.0885 2.57969 12 3.92012C9.90617 2.59729 7.47667 1.90315 5.00002 1.92012C4.27267 1.9231 3.54683 1.98665 2.83002 2.11012C2.59523 2.1506 2.3826 2.27358 2.23044 2.45691C2.07827 2.64025 1.99656 2.87189 2.00002 3.11012V15.1101C1.99788 15.2571 2.02815 15.4027 2.08867 15.5366C2.1492 15.6705 2.23849 15.7894 2.3502 15.8849C2.4619 15.9803 2.59328 16.05 2.73498 16.089C2.87668 16.1279 3.02522 16.1351 3.17002 16.1101C4.60304 15.862 6.07123 15.9032 7.48809 16.2312C8.90495 16.5592 10.2418 17.1675 11.42 18.0201L11.54 18.0901H11.65C11.7609 18.1363 11.8799 18.1601 12 18.1601C12.1202 18.1601 12.2391 18.1363 12.35 18.0901H12.46L12.58 18.0201C13.75 17.1484 15.083 16.5205 16.5002 16.1735C17.9173 15.8265 19.3897 15.7675 20.83 16.0001C20.9748 16.0251 21.1234 16.0179 21.2651 15.979C21.4068 15.94 21.5381 15.8703 21.6498 15.7749C21.7616 15.6794 21.8508 15.5605 21.9114 15.4266C21.9719 15.2927 22.0022 15.1471 22 15.0001V3.00012C21.9896 2.77228 21.9016 2.55483 21.7507 2.38386C21.5997 2.21289 21.3948 2.09866 21.17 2.06012ZM11 15.3501C9.14991 14.3768 7.09054 13.8688 5.00002 13.8701C4.67002 13.8701 4.34002 13.8701 4.00002 13.8701V3.87012C4.33308 3.85093 4.66697 3.85093 5.00002 3.87012C7.13341 3.86776 9.22024 4.49381 11 5.67012V15.3501ZM20 13.9101C19.66 13.9101 19.33 13.9101 19 13.9101C16.9095 13.9088 14.8501 14.4168 13 15.3901V5.67012C14.7798 4.49381 16.8666 3.86776 19 3.87012C19.3331 3.85093 19.667 3.85093 20 3.87012V13.9101ZM21.17 18.0601C20.4532 17.9367 19.7274 17.8731 19 17.8701C16.5184 17.8681 14.0885 18.5797 12 19.9201C9.91154 18.5797 7.48166 17.8681 5.00002 17.8701C4.27267 17.8731 3.54683 17.9367 2.83002 18.0601C2.69985 18.0808 2.57505 18.127 2.46279 18.196C2.35053 18.2651 2.25302 18.3557 2.17589 18.4625C2.09876 18.5694 2.04351 18.6905 2.01333 18.8188C1.98315 18.9471 1.97862 19.0801 2.00002 19.2101C2.05084 19.4698 2.20251 19.6988 2.42181 19.8468C2.64111 19.9949 2.91016 20.05 3.17002 20.0001C4.60304 19.752 6.07123 19.7932 7.48809 20.1212C8.90495 20.4492 10.2418 21.0575 11.42 21.9101C11.5894 22.0307 11.7921 22.0955 12 22.0955C12.2079 22.0955 12.4107 22.0307 12.58 21.9101C13.7582 21.0575 15.0951 20.4492 16.512 20.1212C17.9288 19.7932 19.397 19.752 20.83 20.0001C21.0899 20.05 21.3589 19.9949 21.5782 19.8468C21.7975 19.6988 21.9492 19.4698 22 19.2101C22.0214 19.0801 22.0169 18.9471 21.9867 18.8188C21.9565 18.6905 21.9013 18.5694 21.8242 18.4625C21.747 18.3557 21.6495 18.2651 21.5373 18.196C21.425 18.127 21.3002 18.0808 21.17 18.0601Z" fill="currentColor"></path></svg>'
#   pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-book" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M3 19a9 9 0 0 1 9 0a9 9 0 0 1 9 0"></path><path d="M3 6a9 9 0 0 1 9 0a9 9 0 0 1 9 0"></path><path d="M3 6l0 13"></path><path d="M12 6l0 13"></path><path d="M21 6l0 13"></path></svg>'

[[main]]
  name = "Starters"
  parent = "resources"
  url = "https://gethyas.com/new/"
  weight = 37
  # pre = '<svg data-hk="0-0" width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 "><path d="M21.17 2.06012C20.4532 1.93665 19.7274 1.8731 19 1.87012C16.5184 1.86809 14.0885 2.57969 12 3.92012C9.90617 2.59729 7.47667 1.90315 5.00002 1.92012C4.27267 1.9231 3.54683 1.98665 2.83002 2.11012C2.59523 2.1506 2.3826 2.27358 2.23044 2.45691C2.07827 2.64025 1.99656 2.87189 2.00002 3.11012V15.1101C1.99788 15.2571 2.02815 15.4027 2.08867 15.5366C2.1492 15.6705 2.23849 15.7894 2.3502 15.8849C2.4619 15.9803 2.59328 16.05 2.73498 16.089C2.87668 16.1279 3.02522 16.1351 3.17002 16.1101C4.60304 15.862 6.07123 15.9032 7.48809 16.2312C8.90495 16.5592 10.2418 17.1675 11.42 18.0201L11.54 18.0901H11.65C11.7609 18.1363 11.8799 18.1601 12 18.1601C12.1202 18.1601 12.2391 18.1363 12.35 18.0901H12.46L12.58 18.0201C13.75 17.1484 15.083 16.5205 16.5002 16.1735C17.9173 15.8265 19.3897 15.7675 20.83 16.0001C20.9748 16.0251 21.1234 16.0179 21.2651 15.979C21.4068 15.94 21.5381 15.8703 21.6498 15.7749C21.7616 15.6794 21.8508 15.5605 21.9114 15.4266C21.9719 15.2927 22.0022 15.1471 22 15.0001V3.00012C21.9896 2.77228 21.9016 2.55483 21.7507 2.38386C21.5997 2.21289 21.3948 2.09866 21.17 2.06012ZM11 15.3501C9.14991 14.3768 7.09054 13.8688 5.00002 13.8701C4.67002 13.8701 4.34002 13.8701 4.00002 13.8701V3.87012C4.33308 3.85093 4.66697 3.85093 5.00002 3.87012C7.13341 3.86776 9.22024 4.49381 11 5.67012V15.3501ZM20 13.9101C19.66 13.9101 19.33 13.9101 19 13.9101C16.9095 13.9088 14.8501 14.4168 13 15.3901V5.67012C14.7798 4.49381 16.8666 3.86776 19 3.87012C19.3331 3.85093 19.667 3.85093 20 3.87012V13.9101ZM21.17 18.0601C20.4532 17.9367 19.7274 17.8731 19 17.8701C16.5184 17.8681 14.0885 18.5797 12 19.9201C9.91154 18.5797 7.48166 17.8681 5.00002 17.8701C4.27267 17.8731 3.54683 17.9367 2.83002 18.0601C2.69985 18.0808 2.57505 18.127 2.46279 18.196C2.35053 18.2651 2.25302 18.3557 2.17589 18.4625C2.09876 18.5694 2.04351 18.6905 2.01333 18.8188C1.98315 18.9471 1.97862 19.0801 2.00002 19.2101C2.05084 19.4698 2.20251 19.6988 2.42181 19.8468C2.64111 19.9949 2.91016 20.05 3.17002 20.0001C4.60304 19.752 6.07123 19.7932 7.48809 20.1212C8.90495 20.4492 10.2418 21.0575 11.42 21.9101C11.5894 22.0307 11.7921 22.0955 12 22.0955C12.2079 22.0955 12.4107 22.0307 12.58 21.9101C13.7582 21.0575 15.0951 20.4492 16.512 20.1212C17.9288 19.7932 19.397 19.752 20.83 20.0001C21.0899 20.05 21.3589 19.9949 21.5782 19.8468C21.7975 19.6988 21.9492 19.4698 22 19.2101C22.0214 19.0801 22.0169 18.9471 21.9867 18.8188C21.9565 18.6905 21.9013 18.5694 21.8242 18.4625C21.747 18.3557 21.6495 18.2651 21.5373 18.196C21.425 18.127 21.3002 18.0808 21.17 18.0601Z" fill="currentColor"></path></svg>'
  pre = '<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-template" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 4m0 1a1 1 0 0 1 1 -1h14a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1h-14a1 1 0 0 1 -1 -1z" /><path d="M4 12m0 1a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v6a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z" /><path d="M14 12l6 0" /><path d="M14 16l6 0" /><path d="M14 20l6 0" /></svg>'

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 40

[[social]]
  name = "GitHub"
  pre = '<svg data-hk="0-0" width="32" height="33" viewBox="0 0 32 33" fill="none" xmlns="http://www.w3.org/2000/svg" class="w-8 "><path d="M16 2.5C8.265 2.5 2 8.765 2 16.5C2 22.695 6.0075 27.9275 11.5725 29.7825C12.2725 29.905 12.535 29.485 12.535 29.1175C12.535 28.785 12.5175 27.6825 12.5175 26.51C9 27.1575 8.09 25.6525 7.81 24.865C7.6525 24.4625 6.97 23.22 6.375 22.8875C5.885 22.625 5.185 21.9775 6.3575 21.96C7.46 21.9425 8.2475 22.975 8.51 23.395C9.77 25.5125 11.7825 24.9175 12.5875 24.55C12.71 23.64 13.0775 23.0275 13.48 22.6775C10.365 22.3275 7.11 21.12 7.11 15.765C7.11 14.2425 7.6525 12.9825 8.545 12.0025C8.405 11.6525 7.915 10.2175 8.685 8.2925C8.685 8.2925 9.8575 7.925 12.535 9.7275C13.655 9.4125 14.845 9.255 16.035 9.255C17.225 9.255 18.415 9.4125 19.535 9.7275C22.2125 7.9075 23.385 8.2925 23.385 8.2925C24.155 10.2175 23.665 11.6525 23.525 12.0025C24.4175 12.9825 24.96 14.225 24.96 15.765C24.96 21.1375 21.6875 22.3275 18.5725 22.6775C19.08 23.115 19.5175 23.955 19.5175 25.2675C19.5175 27.14 19.5 28.645 19.5 29.1175C19.5 29.485 19.7625 29.9225 20.4625 29.7825C23.2418 28.8443 25.6568 27.0581 27.3677 24.6753C29.0786 22.2926 29.9993 19.4334 30 16.5C30 8.765 23.735 2.5 16 2.5Z" fill="currentColor"></path></svg>'
  url = "https://github.com/gethyas/hyas"
  weight = 10

[[social]]
  name = "Twitter"
  pre = '<svg viewBox="0 0 24 24" width="32" height="32"><path fill="currentColor" d="M18.244 2.25h3.308l-7.227 8.26 8.502 11.24H16.17l-5.214-6.817L4.99 21.75H1.68l7.73-8.835L1.254 2.25H8.08l4.713 6.231zm-1.161 17.52h1.833L7.084 4.126H5.117z"></path></svg>'
  url = "https://twitter.com/gethyas"
  weight = 20

[[social]]
  name = "Mastodon"
  pre = '<svg viewBox="0 0 16 16" aria-hidden="true" width="32" height="32"><path fill="currentColor" d="M11.19 12.195c2.016-.24 3.77-1.475 3.99-2.603.348-1.778.32-4.339.32-4.339 0-3.47-2.286-4.488-2.286-4.488C12.062.238 10.083.017 8.027 0h-.05C5.92.017 3.942.238 2.79.765c0 0-2.285 1.017-2.285 4.488l-.002.662c-.004.64-.007 1.35.011 2.091.083 3.394.626 6.74 3.78 7.57 1.454.383 2.703.463 3.709.408 1.823-.1 2.847-.647 2.847-.647l-.06-1.317s-1.303.41-2.767.36c-1.45-.05-2.98-.156-3.215-1.928a3.614 3.614 0 0 1-.033-.496s1.424.346 3.228.428c1.103.05 2.137-.064 3.188-.189zm1.613-2.47H11.13v-4.08c0-.859-.364-1.295-1.091-1.295-.804 0-1.207.517-1.207 1.541v2.233H7.168V5.89c0-1.024-.403-1.541-1.207-1.541-.727 0-1.091.436-1.091 1.296v4.079H3.197V5.522c0-.859.22-1.541.66-2.046.456-.505 1.052-.764 1.793-.764.856 0 1.504.328 1.933.983L8 4.39l.417-.695c.429-.655 1.077-.983 1.934-.983.74 0 1.336.259 1.791.764.442.505.661 1.187.661 2.046v4.203z"></path></svg>'
  url = "https://fosstodon.org/@hyas"
  weight = 30

# [[resources]]
#   name = "Documentation"
#   url = "https://docs.gethyas.com/"
#   weight = 10

[[resources]]
  name = "Starter templates"
  url = "https://gethyas.com/new/"
  weight = 20

[[resources]]
  name = "Themes"
  url = "/themes/"
  weight = 30

[[resources]]
  name = "Integrations"
  url = "/integrations/"
  weight = 40

# [[community]]
#   name = "Discussions"
#   url = "https://github.com/orgs/gethyas/discussions"
#   weight = 5

[[community]]
  name = "Community"
  url = "https://community.gethyas.com/"
  weight = 5

[[community]]
  name = "Showcase"
  url = "/showcase/"
  weight = 10

[[community]]
  name = "Contributing"
  url = "https://github.com/gethyas/.github/blob/main/CONTRIBUTING.md"
  weight = 20

# [[community]]
#   name = "Open Collective"
#   url = "https://opencollective.com/hyas"
#   weight = 30

[[documentation]]
  name = "Hyas"
  url = "https://docs.gethyas.com/"
  weight = 10

[[documentation]]
  name = "Images"
  url = "https://images.gethyas.com/"
  weight = 20

[[documentation]]
  name = "Inline SVG"
  url = "https://svg.gethyas.com/"
  weight = 30

[[documentation]]
  name = "SEO"
  url = "https://seo.gethyas.com/"
  weight = 40

# [[about]]
#   name = "Blog"
#   url = "/blog/"
#   weight = 10
# 
# [[about]]
#   name = "Who we are"
#   url = "/about/"
#   weight = 20
# 
# [[about]]
#   name = "Partner with us!"
#   url = "/partnerships/"
#   weight = 30

[[links]]
  name = "Blog"
  url = "/blog/"
  weight = 10

[[links]]
  name = "Doks"
  url = "https://getdoks.org/"
  weight = 20

[[legal]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 10

[[legal]]
  name = "Terms of Service"
  url = "/terms/"
  weight = 20
